### ISSUE TITLE
Hi bro please can you give me the swb file of instagram.apk of airavat rat .......

### ISSUE THREAD

**Issue by KARTIKSORMARE** [Th30neAnd0nly/AIRAVAT#10]
Hi please can you give me swb file of instagram.apk of airavat rat please....

**Comment by KARTIKSORMARE** [comment]
Please give me

**Comment by prateek-chaubey** [comment]
No

**Comment by KARTIKSORMARE** [comment]
Please bro give me swb file of airavat rat project i want 🥲

**Comment by prateek-chaubey** [comment]
@KARTIKSORMARE and i want $1000000000000000000 , please give me bro 🥲

**Comment by KARTIKSORMARE** [comment]
> 

Sorry🙃

**Comment by KARTIKSORMARE** [comment]
I have an error in ohm
