### ISSUE TITLE
This is best rat but some problem need fix ...❤

### ISSUE THREAD

**Issue by diygaming** [Th30neAnd0nly/AIRAVAT#11]
Please Add option to clear old notification.

**Comment by prateek-chaubey** [comment]
There is an option to clear a the previous notifications.

**Comment by krisdowis** [comment]
> There is an option to clear all the previous notifications.

where is the option please?

**Comment by prateek-chaubey** [comment]
![FUCK_YOU](https://user-images.githubusercontent.com/41151614/183958620-4e42ba42-3a26-49f5-979d-0ae1a172cb0d.jpg)
Bottom Right Corner

**Comment by prateek-chaubey** [comment]
@krisdowis Pro Users Only

**Comment by krisdowis** [comment]
ok thank you
