### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by trxshlxrd** [Th30neAnd0nly/AIRAVAT#12]
Hey, your tutorial and tool are very good and well explained, but APK Easy Tool returns an error when trying to recompile the file (even when I try recompiling before modifying it).
Thank you in advance.

(from Windows) 

errors: W: C:\Users\trxsh\Documents\APK Easy Tool\1-Decompiled APKs\Instagram\res\values\ids.xml:20: error: <item> inner element must either be a resource reference or empty.

I got many like that, all from ids.xml (using aapt2)

![image](https://user-images.githubusercontent.com/87191070/173825128-03da01a5-5dfe-4263-9388-23d0278a7276.png)

**Comment by trxshlxrd** [comment]
W: C:\Users\trxsh\AppData\Local\apktool\1-Decompiled APKs\Instagram2\AndroidManifest.xml:20: error: No resource identifier found for attribute 'requestLegacyExternalStorage' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\trxsh\AppData\Local\Temp\brut_util_Jar_42531454655738416651665107103423995756.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 28, --version-code, 1, --version-name, 1.0.0-alpha, --no-version-vectors, -F, C:\Users\trxsh\AppData\Local\Temp\APKTOOL9110546481042518919.tmp, -e, C:\Users\trxsh\AppData\Local\Temp\APKTOOL1493660469584457336.tmp, -0, arsc, -I, C:\Users\trxsh\AppData\Local\apktool\framework\1.apk, -S, C:\Users\trxsh\AppData\Local\apktool\1-Decompiled APKs\Instagram2\res, -M, C:\Users\trxsh\AppData\Local\apktool\1-Decompiled APKs\Instagram2\AndroidManifest.xml]
Compile failed. Please read the log

**Comment by prateek-chaubey** [comment]
Try APKTOOL M
