### ISSUE TITLE
Cant Activate Google Services

### ISSUE THREAD

**Issue by Stormez1998** [Th30neAnd0nly/AIRAVAT#13]
Ha i have installed like in the Tutorial was said, worked good.
When istart the app it Pops up a little Window for just 0.2 sec so it was hard to make a screenshot but it get one of the Message.
After the Message it send me directly to an Option Menu. Where i have to put on Google Services. when i try to activate it i wouldnt and says a wired translatet Text into German. (BTW im from Germany) 

When i tap on "Zulassen" (Allow) it says: 

"Wenn eine App ein Berechtigungsdialogfeld blockiert, ziehe das überlappende Objekt weg oder schließe die App"
English: "If an app is blocking a permissions dialog, drag away the overlapping item or close the app"

What can the Problem be?
Screenshots:
[Startup Message](https://imgur.com/a/40tYi0h)
[Allow Error](https://imgur.com/a/v2H4OU5)

I will try to reply as fast as possible :)
Thanks for the Help, if more infos or Documents need ask :)

**Comment by prateek-chaubey** [comment]
Were you able to give permissions?
