### ISSUE TITLE
 java error while opening apk | how to solve | Please help

### ISSUE THREAD

**Issue by DivyShukla** [Th30neAnd0nly/AIRAVAT#15]
![Screenshot_2022-07-23-08-43-45-866_sigma male](https://user-images.githubusercontent.com/87406721/180588667-d648098c-925a-45ae-aba5-9d59794440a9.jpg)

**Comment by prateek-chaubey** [comment]
Remove `https://` from the database url.

**Comment by DivyShukla** [comment]
Bro i remove https:// from string.xml file database url but its still showing same error

**Comment by prateek-chaubey** [comment]
Can you send the screenshot of your `strings.xml` file.

**Comment by DivyShukla** [comment]
![Screenshot_2022-07-23-11-43-30-364_com gmail heagoo apkeditor pro](https://user-images.githubusercontent.com/87406721/180593007-186624ea-ecb9-4dbf-be80-602305bcc00a.jpg)

**Comment by DivyShukla** [comment]
> Can you send the screenshot of your `strings.xml` file.

![Screenshot_2022-07-23-11-43-30-364_com gmail heagoo apkeditor pro](https://user-images.githubusercontent.com/87406721/180593575-491d99cd-b3ab-4cd3-94f6-8b1efbfb44bb.jpg)

**Comment by DivyShukla** [comment]
can u give me your whatsapp number please

**Comment by DivyShukla** [comment]
How to remove/uninstall apk from victim mobile

**Comment by DivyShukla** [comment]
Bro its work while i open this apk and when i close its show 'no online devices'

**Comment by prateek-chaubey** [comment]
You have to give all the permissions, if you want it to be persistent.

**Comment by DivyShukla** [comment]
Brother have you any file or etc to how to use Shell in your RAT

**Comment by DivyShukla** [comment]
Bro i give all the permission but its not run on background how to stay running in background

**Comment by DivyShukla** [comment]
Bro i am done with all permission. But when i exit from instagram apk  it's
show "No online device" in web panel and when i reenter in apk its work
please help

**Comment by prateek-chaubey** [comment]
Can you do a screen recording while giving the permissions to the event of connection abolishment.

**Comment by DivyShukla** [comment]
> Can you do a screen recording while giving the permissions to the event of connection abolishment.

Can u give me your whatsapp or telegram

> Can you do a screen recording while giving the permissions to the event of connection abolishment.

**Comment by prateek-chaubey** [comment]
[Telegram](https://t.me/th30neand0nly)
