### ISSUE TITLE
Step by step deailt guide line

### ISSUE THREAD

**Issue by tehseensagar** [Th30neAnd0nly/AIRAVAT#2]
Hi,
I'm new to firebase stuff. would you mind explaining a bit in details step by step to configure this. I have done data base and storage part not stuck with hosting ?

**Comment by prateek-chaubey** [comment]
It's not necessary that you have to use firebase hosting ,  you can use localhost instead.

**Comment by ChillVibesMushroom** [comment]
> Hi, I'm new to firebase stuff. would you mind explaining a bit in details step by step to configure this. I have done data base and storage part not stuck with hosting ?

can you make a video bro save us the time

**Comment by prateek-chaubey** [comment]
@ChillVibesMushroom There are 1000+ videos available on youtube , I don't think that it will take more than 10 seconds to search.
Whereas to save your time here is the video.
https://t.me/c/1526837741/2928
