### ISSUE TITLE
notifications ando keylogger

### ISSUE THREAD

**Issue by FabriSC** [Th30neAnd0nly/AIRAVAT#20]
any way for recent notifications to be seen first also with keylogger?

**Comment by prateek-chaubey** [comment]
Everything is working perfectly, just you need to give all the required permissions.

**Comment by prateek-chaubey** [comment]
No

**Comment by FabriSC** [comment]
You can at least raise the amount of notifications to see from 10 to 500 in "load more"

**Comment by prateek-chaubey** [comment]
First of all the limit is 20 nodes and second It would cause performance issue on web browsers if you will try to load too much data.
