### ISSUE TITLE
incluid vps

### ISSUE THREAD

**Issue by FabriSC** [Th30neAnd0nly/AIRAVAT#21]
Is there any way to configure with a vps instead of firebase? firebase has a very short limit

**Comment by prateek-chaubey** [comment]
Firebase is stable , easy to configure and have multi-platform support.
Whereas not everyone have access to VPS.
90% of people using this tool are students.

**Comment by FabriSC** [comment]
If I have access to some vps accounts, I was wondering, is there any way to link arivat with vps?
