### ISSUE TITLE
Play music command not working

### ISSUE THREAD

**Issue by krisdowis** [Th30neAnd0nly/AIRAVAT#22]
when i use the play music command it doesn't work

instead it says 
Response  ERROR: Song Not Found from URL

but when i input song url into browser it plays

**Comment by prateek-chaubey** [comment]
You need to give direct file URL containing `.mp3` file in the command.
For more info check here https://t.me/th30neand0nly0ne/12

**Comment by krisdowis** [comment]
[](url)

> You need to give direct file URL containing `.mp3` file in the command. For more info check here https://t.me/th30neand0nly0ne/12

i did already

**Comment by krisdowis** [comment]
https://im.ge/i/OsCk40
https://im.ge/i/OsCHsT

**Comment by krisdowis** [comment]
> > You need to give direct file URL containing `.mp3` file in the command. For more info check here https://t.me/th30neand0nly0ne/12
> 
> i did already

ohhhh 
only google drive files are allowed
i was using my own file 

file:///home/hp/Music/Tion-x-Russ-Millions-Body-Remix-Ft.Arrdee-E1-Bugzy-Fivio-ZT-Darkoo-Buni-Lyric-Video.mp3

**Comment by krisdowis** [comment]
so i cant play local files even if i host the web panel on my localhost or public ip

**Comment by prateek-chaubey** [comment]
You can use any file from the web which is accessible to everyone.

**Comment by krisdowis** [comment]
and how to create airavat ios payload with firebase
