### ISSUE TITLE
How to remove duplicate devices on device list? 

### ISSUE THREAD

**Issue by mountaincastle47** [Th30neAnd0nly/AIRAVAT#26]
???

**Comment by prateek-chaubey** [comment]
Can you share a screenshot of your web panel containing duplicate devices.

**Comment by mountaincastle47** [comment]
Here it is
![Uploading Screenshot_20220905-141156.png…]()

**Comment by mountaincastle47** [comment]
![Screenshot_20220905-141156](https://user-images.githubusercontent.com/66811246/188365306-b15e67fa-bd12-459d-b178-ba96a254c026.png)

**Comment by prateek-chaubey** [comment]
This is due to unexpected removal of RAT from the device. It seems to be firebase bug or maybe something else.
Try clearing your firebase database.
