### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Aditya36363** [Th30neAnd0nly/AIRAVAT#27]
1.The Shell Command is totally useless When Ever I type Any Commands even a simple one it does not  work
2. Keylogger is good but i can't keep scrolling and clicking There should be easier way to do it
3.there is no login portal in  panel if the link is the only way to access. anyone can access without the admin permission
4. There should be option of the app like auto clicker or when we want we can click on victim screen 
5. The admin panel also hangs sometime

**Comment by prateek-chaubey** [comment]
1. Can you list the commands which you have used.
2. For better performance , only fewer records are loaded at a time.
3. Use localhost or your private vps.
4. Why?
5. Can you record a video and elaborate more , upon how to reproduce this.

**Comment by Aditya36363** [comment]
1.man,cat,echo
2.yeah But there should Option To record ONLY WhatsApp messages . whenever WhatsApp open the Keylogger should start automatically
3.but login page Looks Good i can access it from any device most probably But not needed Now
4.Cause its like using the Phone we can do more functions
5.i given it at telegram

**Comment by Aditya36363** [comment]
> 1. Can you list the commands which you have used.
> 2. For better performance , only fewer records are loaded at a time.
> 3. Use localhost or your private vps.
> 4. Why?
> 5. Can you record a video and elaborate more , upon how to reproduce this.

**Comment by Aditya36363** [comment]
1.man,cat,echo
2.yeah But there should Option To record ONLY WhatsApp messages . whenever WhatsApp open the Keylogger should start automatically
3.but login page Looks Good i can access it from any device most probably But not needed Now
4.Cause its like using the Phone we can do more functions
5.i given it at telegram

**Comment by prateek-chaubey** [comment]
1. cat , echo and all other adb commands are working perfectly, seems like you have some issue on your end. If you can share some screenshots it would be better.
2. This isn't how keylogger is meant to work.
3. Use localhost or a private VPS.
4. Ok!!
5. Where?

**Comment by FabriSC** [comment]
any tutorial to make it work on vps?

**Comment by prateek-chaubey** [comment]
It's the same process you do on your local computer.
The only difference is you will be doing that on VPS.
