### ISSUE TITLE
False Claim 

### ISSUE THREAD

**Issue by roobini-gamer** [Th30neAnd0nly/AIRAVAT#29]
![Screenshot 2022-10-23 at 08-52-48 AIRAVAT](https://user-images.githubusercontent.com/69848832/197396124-fadb38e6-67dc-4344-9c53-ecf009748d79.png)

when you say "This is an Open Source RAT" means you provided actually **Source Code** not **Obfuscated JS**

**Comment by prateek-chaubey** [comment]
LOL

**Comment by roobini-gamer** [comment]
understand that you want other not resell the software and there is absolutely no way to stop bad actors if they can't use this Ohm and other remote access trojans will be used instead
Obfuscated JS isn't Opensource and yes "obfuscated or encrypted" matter how you expect users to understand how AIRAVAT actually works if they cant take a closer look at it in first place or Contributing to it 
seems you're hiding something in that code and dont want others know about it *probably because forks will be better than pro version*
