### ISSUE TITLE
Strongly request for remove footer text

### ISSUE THREAD

**Issue by MRFOX777** [Th30neAnd0nly/AIRAVAT#3]
Please remove this footer text (We support Ukraine and condemn war. Push Russian government to act against war. Be brave, vocal and show your support to Ukraine. Follow the latest news HERE) or move somewhere this text . having some problem for this footer text . specially facing problem when time using from smartphone. And thank you bro for your wonderful work. Wish your bright future in this field. Your work our inspiration. and I promise I use this for good

**Comment by prateek-chaubey** [comment]
I haven't added the footer in my code.
Seems like you are using `000webhost` , it's automatically added by them in each and every page.
