### ISSUE TITLE
There is no option to download data.

### ISSUE THREAD

**Issue by Amadiya69** [Th30neAnd0nly/AIRAVAT#38]
How to download victim's data??

Only 3 options are visible.. 
Open, Delete and encrypt !!! Then there is no option. 

How to download userdata of victim in Airavat??

Plzz bro quickly solve this problem ❤️

**Comment by prateek-chaubey** [comment]
Seems like you haven't read the Readme correctly.
First of all the pro version you are using isn't the real one.
It may contain backdoor and others can see your private data.
And second don't open unnecessary issues.
