### ISSUE TITLE
Victim phone’s message can’t be read.

### ISSUE THREAD

**Issue by devilniladdin** [Th30neAnd0nly/AIRAVAT#4]
Victim phone’s message can’t be read. Message showing ## . Please solve is as soon as possible.

**Comment by prateek-chaubey** [comment]
Which message?

**Comment by devilniladdin** [comment]
Hello sir , 
I hope you are well . I am also good. But I am really so sorry to inform you that 
This rat doesn't work properly. Sometimes it's loading or stop. Victim phone message can't be read . All kind of Message show error or a shas(#) code . Sometimes this rat stop automatically and all phone not support and some antivirus software detect the rat apk . I request you to update it. Sir , please add some features such as open camera;location;gallery; default browser open.; Auto hide apk ; add some wallpaper . That's all
