### ISSUE TITLE
Infite loading 

### ISSUE THREAD

**Issue by Annxhilator** [Th30neAnd0nly/AIRAVAT#40]
I did everything right but I'm having a infinite loading screen

**Comment by prateek-chaubey** [comment]
1. Are you using 000webhost?
2. Can you share some screenshots?
3. Check your Firebase Console for quota limitations.
4. Make sure that you have hosted all the resources correctly.

**Comment by Annxhilator** [comment]
> 1. Are you using 000webhost?
> 2. Can you share some screenshots?
> 3. Check your Firebase Console for quota limitations.
> 4. Make sure that you have hosted all the resources correctly.

![Screenshot_20221229-070543.png](https://user-images.githubusercontent.com/105570214/209936029-a9cbfc65-2a99-4c0d-bcdb-083cd61d6247.png)
 Yeah using webhost. Hosted 6 files to the site

**Comment by prateek-chaubey** [comment]
Use localhost or firebase hosting
You can find all the resources at [Airavat Rat](https://t.me/AiravatRat)

**Comment by Annxhilator** [comment]
Using localhost on port 8383 , the problem persists,
