### ISSUE TITLE
Victim are Not Visible in Control panel

### ISSUE THREAD

**Issue by Aditya36363** [Th30neAnd0nly/AIRAVAT#42]
The Airavat was working good But after time the Airavat does not show any victims also there is duplicate device bug
Last and very important That you should add custom webview Your Rat's  Instagram Url is Decoded and Can't be changeable

**Comment by prateek-chaubey** [comment]
1. Try clearing your firebase database, this bug is due to sudden disconnection.
2. Won't be added
