### ISSUE TITLE
Next Update ?

### ISSUE THREAD

**Issue by XR-47** [Th30neAnd0nly/AIRAVAT#45]
𝚆𝚑𝚎𝚗 𝚈𝚘𝚞 𝚠𝚒𝚕𝚕 𝚞𝚙𝚍𝚊𝚝𝚎 𝚝𝚑𝚒𝚜 𝚝𝚘𝚘𝚕
𝙰𝚗𝚍 𝙰𝚍𝚍 𝚜𝚘𝚖𝚎 𝙽𝚎𝚠 𝙵𝚎𝚝𝚞𝚛𝚎𝚜 !

**Comment by prateek-chaubey** [comment]
Probably in future
