### ISSUE TITLE
Sms Are Encrypted

### ISSUE THREAD

**Issue by XR-47** [Th30neAnd0nly/AIRAVAT#46]
![Screenshot_20230114-095531_Chrome](https://user-images.githubusercontent.com/92029487/212450203-5956c160-8c9e-4796-9fa9-cb727c043384.jpg)

**Comment by prateek-chaubey** [comment]
These are not encryptions, but an incorrect encoding.

**Comment by XR-47** [comment]
It’s can be fixed?

**Comment by XR-47** [comment]
> These are not encryptions, but an incorrect encoding.

How can i fix this?
