### ISSUE TITLE
App not woking 

### ISSUE THREAD

**Issue by Adithyan007hack** [Th30neAnd0nly/AIRAVAT#47]
Hello 
Bro when I Compiled and opened the app its not working and giving me error
![photo_2023-01-16_21-26-42](https://user-images.githubusercontent.com/87800041/212720344-2ee4dc61-ef24-4c82-995a-536d51f8f1b2.jpg)
![photo_2023-01-16_21-26-45](https://user-images.githubusercontent.com/87800041/212720354-8b5a2c25-11bc-484d-b1d4-7d8f06f9e760.jpg)
![photo_2023-01-16_21-26-47](https://user-images.githubusercontent.com/87800041/212720361-80f45289-de56-4ba8-9b9d-ece351dadd06.jpg)

Android version: 8.1

**Comment by prateek-chaubey** [comment]
Remove `gs://`  from Firebase Storage URL.

**Comment by Adithyan007hack** [comment]
Bro the app has been set up correctly but it the web host just say processing nothing else
I am using github for hosting

**Comment by prateek-chaubey** [comment]
You may not have hosted `script.js` file.
Follow the tutorial videos provided on github.
