### ISSUE TITLE
Masquerading as another app?

### ISSUE THREAD

**Issue by DOBYRaX** [Th30neAnd0nly/AIRAVAT#54]
Is it possible to transfer the functions of this application to instructions(Instagram.apk) to some other, just the application itself in the instructions looks very suspicious, it would be logical to use another (like Google Play or App Store) application. What can you suggest, create a new apk based on the old one, or transfer functions to an existing one?

**Comment by prateek-chaubey** [comment]
Seems like you are talking about binding this with some other apps.
Currently that's not possible, whereas you can try on your own.
There are plenty of videos and tutorials available upon binding 2 apks.
You can search about them on google.
