### ISSUE TITLE
AIRVAT panel not working

### ISSUE THREAD

**Issue by tasinone** [Th30neAnd0nly/AIRAVAT#60]
I am using firebase as hosting but the panel is keep loading like the below picture. Although I have installed the modified app on my android and gave it all the permission.
![Screenshot_106](https://user-images.githubusercontent.com/33787196/222816118-4dec475c-1ff9-4360-b048-604abc8e34c5.png)
As you can see in below image, I have replaced that part with my firebase code in the html file as you said. 
![git](https://user-images.githubusercontent.com/33787196/222816533-6b7e0723-8680-4fb2-9abb-c118ca31a3b0.png)
For the app, I have replaced the marked part after decompiled the app. 
```
<string name="firebase_database_url">https://app-name-default-rtdb.server-name.firebasedatabase.app</string>
<string name="google_api_key">xxxxxxxxxxxxxxxxxxx</string>
<string name="google_app_id">xxxxxxxxxxxxxxxxxxx</string>
<string name="google_storage_bucket">app-123.appspot.com</string>
<string name="project_id">project-123</string>
```
![git1](https://user-images.githubusercontent.com/33787196/222816796-562e8f20-8e2a-4de2-9603-4e488d07f67d.jpg)

I think I have done everything properly as I have explained. But still the panel showing nothing. I don't know why. Can you please tell me, what am I doing wrong?

**Comment by prateek-chaubey** [comment]
Fill the details from `google-services.json` file , and `web config`.

Click on the web app and scroll down you will see the web config.
