### ISSUE TITLE
noob maybe

### ISSUE THREAD

**Issue by Grunt6164** [Th30neAnd0nly/AIRAVAT#61]
I have checked and rechecked everything several times. I used both the written instructions and the video tut as reference. However the web panel seems to not be working correctly, when done like video when i go to site it simply shows the index. Html code.

Also with the firebase when i click on "deploy" section it simply refers me back to my page which says nothing has been deployed... 

I need some guidance

**Comment by prateek-chaubey** [comment]
Probably if you have followed the video correctly then everything should have been working.
Seems like you may have mistaken on some step.
Please follow the video tutorial again by creating a new firebase project.
Also do share some info.
1. Which hosting provider are you using?
2. Have you modified the web config?
3. Have you compiled the app correctly?
