### ISSUE TITLE
record audio does not work (stuck loading at "processing)

### ISSUE THREAD

**Issue by thrqrm** [Th30neAnd0nly/AIRAVAT#62]
Hello, i'm facing an issue where i can't able to record audio with the device, i have had opened this issue earlier (https://github.com/Th30neAnd0nly/AIRAVAT/issues/59), i already tried to host on firebase hosting and checked the permission on the device and it's already set to "allow". other function works perfectly (notification, torchlight, vibrate, and other functions), it's only the record audio that seems not working. Is there any accessibility option that i should turn on to make the function works properly? would you please give any suggestions and solutions to this issue? thank you.

**Comment by prateek-chaubey** [comment]
There isn't any issue with the hosting or web panel.
Try relaunching the app , probably because RAT has been removed from recents activity therefore the recording feature isn't working.
