### ISSUE TITLE
Disconnect devices still shows connected but not working 

### ISSUE THREAD

**Issue by saqibbhai483** [Th30neAnd0nly/AIRAVAT#66]
I hacked many devices . Some of devices automatically remove from my victim list when victim uninstall tha instagram rat file .
But some devices after uninstalling they still shows in my victims list 

How can I remove manual

Please help me #victimlist

**Comment by Prisoner2-6-7** [comment]
> I hacked many devices . Some of devices automatically remove from my victim list when victim uninstall tha instagram rat file .
> But some devices after uninstalling they still shows in my victims list 
> 
> How can I remove manual
> 
> Please help me #victimlist

You have to wait for hours to get updated. Or clear the database in the firebase.

**Comment by Prisoner2-6-7** [comment]
You have to wait for hours to get updated. Or clear the firebase database.
