### ISSUE TITLE
How to change app url

### ISSUE THREAD

**Issue by henrygreen311** [Th30neAnd0nly/AIRAVAT#83]
Hello sir, please how can i change the app url to Facebook url, please 🙏🙏🙏 give me a reply. thanks

**Comment by prateek-chaubey** [comment]
You can't because it's already binded with Instagram Webview Phishing

**Comment by henrygreen311** [comment]
Okay, but sir please how about removing the webview phishing to complete my action. please help me out 🙏🙏🙏
