### ISSUE TITLE
Processing 

### ISSUE THREAD

**Issue by Cyberkingcr7** [Th30neAnd0nly/AIRAVAT#91]
![Screenshot_2023-12-27-00-49-46-552_com android chrome](https://github.com/Th30neAnd0nly/AIRAVAT/assets/70591379/f195b18c-aaad-4067-9c23-fc3e8e593cad)
Please help fix this

**Comment by jamilahmed2** [comment]
What about IOS victims ?

**Comment by prateek-chaubey** [comment]
You have to host all the files , but you have only hosted `index.html`

**Comment by CubicPython-Official** [comment]
Hi, how to host all the files? Can you make a tutorial please?
